Iter1
adettelle/go-keeper pull request #1
Opened 2024-11-25 17:09 UTC by adettelle

Сервер реализует следующую логику:
    • регистрация, аутентификация и авторизация пользователей;
    • хранение приватных данных;

Клиент реализует следующую логику:
    • аутентификация и авторизация пользователей на удалённом сервере;
    • доступ к приватным данным по запросу.

Создание, редактирование и удаление данных происходит на стороне сервера.
В README.md имеется описание, чтобы запустить приложение.

2024-11-29 13:55 UTC, capsulated requested changes
Очень простенький README.md получился, и запустить у меня не получилось =( Нужно детальные описать все шаги, минимальные требования, пример переменных и команды запуска: чтобы не 'гадая' с помощью пары команд запустить само приложение и тесты. В принципе, указал это в коментах.

Повторюсь, на 1-1 намного проще и быстрее будет демонстрировать и рассказывать про свою работу, также больше возможностей мне объяснить возможные подходы, альтернативы, лучшие и плохие практики, привести аналогии.

На крайний случай можно записать скринкаст с демонстрацией запуска и работы с проектом (регистрация, аунтификация, работа со всеми типами данных). И хотелось бы рассказ или описание с выбранными решениями.

По структуре пакетов и файлов - всё очень хорошо, ориентироваться в проекте просто и ясно где что.

Продолжай работу в этом же pull request'е, чтобы финальная работа была целиком в одном PR. Если что, пиши в пачку напрямую, могу отвечать на вопросы по этим замечаниям

2024-11-29 13:55 UTC, capsulated commented on README.md
> +## yandex practicum final task
Необходимо детально и развёрнуто составить README.md, для того, чтобы можно было с лёгкостью и без проблем запустить сервис и тесты. Сделать содержание, с минимальными необходимыми требованиями по установке и запуску, начальный запуск, работа с сервисом. Также, обязательно описать особенности и выбранные решения: способ синхронизации, что и где шифруется, может диаграммы/рисунки добавить и тп, короче полноценную документацию. Цель: однозначно и успешно запустить проект, скажем, на сервере (это для примера) и 'подсветить' выбранные подходы

2024-11-29 13:55 UTC, capsulated commented on README.md
> +JWT_SIGNKEY
Для этих переменных хотелось бы также дефолтные значения, либо какие-то скрипты (bash или makefile, может непосредственно Docker образ с приложением). JWT_SIGNKEY - что за флаг? В нём json-строка должны быть? Или секретный ключ? А SECRET_ACCESSKEY - это тогда что? Не смог разобраться чтобы запустить

2024-12-04 15:55 UTC, adettelle commented
Чтобы запустить приложение в текущем виде, надо запустить команду `make run-all` – это запустит сервер со всем необходимым.
Клиент пока можно запускать командой `go run ./cmd/client --help`. Это выдаст список команд.
Далее надо зарегистрироваться и залогиниться или зарегистрироваться с флагом -s. Это с автоматической аутентификацией. 
Пока работаю над тем, чтобы сделать кросс платформенные сборки на гитхабе, пишу документацию и тесты. Но хотела показать, что и как пока работает.

2025-11-17 12:25 UTC, merged